[toolchain]
channel = "nightly"
components = [
    "rust-src",
    "cargo",
    "clippy",
    "llvm-tools",
    "rust-analyzer",
    "rustfmt",
    "rustc-codegen-cranelift-preview",
]
targets = ["wasm32-unknown-unknown", "x86_64-unknown-linux-gnu"]
